# Generated by Django 3.1.5 on 2021-01-19 08:38

from django.db import migrations, models
import django.db.models.deletion
import mainApps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=20)),
                ('isNeutered', models.CharField(choices=[('T', 'TRUE'), ('F', 'FALSE'), ('U', 'UNKNOWN')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('U', 'UNKNOWN')], max_length=1)),
                ('feature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ImageTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainApps.models.image_path)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=mainApps.models.image_path)),
                ('checkIn', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApps.cat')),
            ],
        ),
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainApps.models.image_path)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApps.catpost')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='favoriteKitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainApps.kitchen'),
        ),
    ]
