# Generated by Django 3.1.5 on 2021-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='checkIn',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='checkIn',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='feeding',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
