# Generated by Django 3.1.5 on 2021-01-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='gender',
            field=models.CharField(choices=[('M', '남자'), ('F', '여자'), ('U', '알수없음')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cat',
            name='isNeutered',
            field=models.CharField(choices=[('T', '중성화 O'), ('F', '중성화 X'), ('U', '알수없음')], max_length=1),
        ),
        migrations.RemoveField(
            model_name='catmention',
            name='mention',
        ),
        migrations.AddField(
            model_name='catmention',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApps.mention'),
        ),
        migrations.RemoveField(
            model_name='emergencymention',
            name='mention',
        ),
        migrations.AddField(
            model_name='emergencymention',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApps.mention'),
        ),
        migrations.RemoveField(
            model_name='kitchenmention',
            name='mention',
        ),
        migrations.AddField(
            model_name='kitchenmention',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApps.mention'),
        ),
    ]
