# Generated by Django 3.1.2 on 2021-01-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='feeding',
        ),
        migrations.AddField(
            model_name='user',
            name='recentCheckin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recentCheckin', to='mainApps.kitchen'),
        ),
    ]
