# Generated by Django 3.1.5 on 2021-01-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0002_auto_20210121_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
