# Generated by Django 3.1.5 on 2021-01-21 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApps', '0003_auto_20210121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymention',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApps.cat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
